# Generated by Django 5.1.6 on 2025-10-04 16:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0002_alter_producto_precio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="precio",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Precio",
            ),
        ),
        migrations.CreateModel(
            name="Transaccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_transaccion_payu",
                    models.CharField(
                        help_text="Transaction ID de PayU", max_length=255, unique=True
                    ),
                ),
                (
                    "estado_pol",
                    models.CharField(
                        help_text="Estado de la transacción en PayU", max_length=50
                    ),
                ),
                (
                    "mensaje_respuesta",
                    models.CharField(
                        help_text="Mensaje de respuesta de PayU", max_length=255
                    ),
                ),
                (
                    "metodo_pago_nombre",
                    models.CharField(
                        help_text="Nombre del método de pago usado", max_length=100
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("moneda", models.CharField(max_length=10)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "pedido",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transacciones",
                        to="tienda.pedido",
                    ),
                ),
            ],
        ),
    ]
