# Generated by Django 5.1.6 on 2025-10-04 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0003_alter_producto_precio_transaccion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pedido",
            name="metodo_pago",
        ),
        migrations.DeleteModel(
            name="MetodoPago",
        ),
    ]
